Capstone Project
renercrows/Pokedex-API pull request #6
Opened 2022-09-09 00:57 UTC by renercrows

I created a webpage calling a Pokemon API and returning the data, I used Redux and did some testing on it.

### Click the logo to get to the home page, if not you won't be able to see pokemons.

Video:
https://www.loom.com/share/6dabf9cf2b074f9192e45ea4d64557b0

2022-09-09 02:08 UTC, Davidosky007 requested changes
Hi @renercrows 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* No linter errors 👍 
* Good video presentation 👍 
* All tests passed ✔️ 
* Proper use of Gitflow 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 02:08 UTC, Davidosky007 commented on README.md
> +
* Kindly ensure your README contains an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-09-09 02:08 UTC, Davidosky007 commented on public/index.html
> -    />
* Kindly add back your public folder and index.html file as without this your react app wont be able to run, i can see you have deleted them 🙏

2022-09-09 02:08 UTC, Davidosky007 commented on src/components/Api.js
> +        setPokemons((pokemons) => [...pokemons, pokemon]);
* Kindly ensure that all data retrieved from the API should be stored in the Redux store this is a[ requirement ](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=The%20data%20retrieved%20from%20the%20API%20should%20be%20stored%20in%20the%20Redux%20store)

2022-09-09 02:08 UTC, Davidosky007 commented on src/components/DisplayPokemons.js
> +  // console.log(pokemons);
* Kindly remove all commented code from your codebase as it makes your code bulky and looks unprofessional

2022-09-09 02:08 UTC, Davidosky007 commented on src/components/SingleCard.js
> +    fetchData();
* Kindly ensure that all data retrieved from the API should be stored in the Redux store [Checkout the technical requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=The%20data%20retrieved%20from%20the%20API%20should%20be%20stored%20in%20the%20Redux%20store)

2022-09-09 02:08 UTC, Davidosky007 commented on src/components/SinglePokemon.js
> +    }
* Kindly ensure that all data retrieved from the API should be stored in the Redux store [Checkout the technical requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=The%20data%20retrieved%20from%20the%20API%20should%20be%20stored%20in%20the%20Redux%20store)

2022-09-09 02:08 UTC, Davidosky007 commented on src/index.css
> +}
* Currently when i click on the details page i can't find the back button kindly add this as it improves the user experience of your application [Check details page requirement here ](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=When%20the%20user%20clicks%20on%20the%20%22Back%22%20button%20(%3C)%2C%20the%20user%20navigates%20to%20the%20home%20page.)
![image](https://user-images.githubusercontent.com/52497246/189257324-103b1824-1a02-4f35-b922-d9341c0b2cd8.png)

2022-09-09 02:08 UTC, Davidosky007 commented on src/pages/PokemonData.js
> +      );
* Kindly ensure that all data retrieved from the API should be stored in the Redux store [Checkout the technical requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=The%20data%20retrieved%20from%20the%20API%20should%20be%20stored%20in%20the%20Redux%20store)

2022-09-09 02:08 UTC, Davidosky007 commented on src/utils/FetchCards.js
> +};
* Kindly ensure that all data retrieved from the API should be stored in the Redux store [Checkout the technical requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=The%20data%20retrieved%20from%20the%20API%20should%20be%20stored%20in%20the%20Redux%20store)

2022-09-09 05:03 UTC, smunozmo requested changes
Hi @renercrows, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- You have done an excellent job on this project, congrats on it! 👏 
- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 05:03 UTC, smunozmo commented on src/components/SingleCard.js
> +    fetchData();
- [ ] Your app is looking great, congrats on it! 🎉 However, as the previous reviewer said, the data fetched from the API should be stored in the Redux store:

<img width="967" alt="Screen Shot 2022-09-08 at 11 57 49 PM" src="https://user-images.githubusercontent.com/83717285/189274847-40c616a6-7fe8-42ce-a348-15ec2294a377.png">

2022-09-09 05:03 UTC, smunozmo commented on src/components/SinglePokemon.js
> +    }
- [ ] You are almost there! Let's try to store the retrieved data from the API in the Redux store as the previous reviewer said.

2022-09-09 05:03 UTC, smunozmo commented on src/components/DisplayPokemons.js
> +  // console.log(pokemons);
- [ ] Your app is working properly, excellent job! I would suggest cleaning up any unused code like this comment to keep it professional as this is a cool project for your portfolio.

2022-09-09 05:03 UTC, smunozmo commented on src/components/Api.js
> +        setPokemons((pokemons) => [...pokemons, pokemon]);
- [ ] Nice job, you are almost ready! It would be great if you addressed this change suggested by the previous reviewer.

2022-09-10 18:13 UTC, mateo951 approved these changes
### Hi @renercrows, 

Well done implementing all the changes required by the previous reviewer 🔥
In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it 🚀 

### Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-09-10 21:41 UTC, merged